version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/automotive/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
