name: Bug Report
description: Report a bug or malfunction in the Automotive OS SDK
title: "[BUG] Descriptive title of the issue"
labels: [bug]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## Describe the bug
        A clear and concise description of the issue you're experiencing.

  - type: textarea
    id: describe-bug
    attributes:
      label: Describe the bug
      description: What went wrong? Be clear and concise.
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## To Reproduce
        Provide detailed information to help us reproduce the issue.

  - type: input
    id: sdk-version
    attributes:
      label: SDK version
      placeholder: e.g. v1.2.3
    validations:
      required: true

  - type: input
    id: target-platform
    attributes:
      label: Target platform
      placeholder: e.g. Automotive Grade Linux, Android Automotive
    validations:
      required: true

  - type: input
    id: hardware
    attributes:
      label: Hardware
      placeholder: e.g. Renesas R-Car H3, x86 VM, Raspberry Pi
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: |
        List the steps to reproduce the issue, e.g.:
        - Launch component X
        - Call method Y
        - Observe unexpected behavior
      placeholder: |
        1. ...
        2. ...
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: screenshots-logs
    attributes:
      label: Screenshots / Logs
      description: Add any relevant screenshots or logs
      placeholder: Paste logs or drop images here

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Any other context or information

  - type: input
    id: jira
    attributes:
      label: Jira (if applicable)
      description: Paste the link to the corresponding Jira ticket
      placeholder: https://jira.yourcompany.com/browse/SDK-123
