name: Run Code Quality with Detekt

on:
  pull_request:
    branches:
      - 'develop'
    types: [opened, reopened, synchronize, edited]

permissions:
  contents: read
  pull-requests: write

jobs:
  code-quality:
    name: Code Quality
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      - name: Run detekt
        id: run-detekt
        run: ./gradlew detekt

      - name: Upload detekt reports
        uses: actions/upload-artifact@v4
        with:
          name: detekt-report
          path: '**/build/reports/detekt'

      - name: Comment on PR
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions/github-script@v7
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const outcomeDetekt = '${{ steps.run-detekt.outcome }}';
                      
            const detektMessage = outcomeDetekt === 'success' 
              ? `✅ CodeQuality with detekt passed successfully!`
              : `❌ CodeQuality checks failed. Please check the detekt report artifact.`;
            
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: detektMessage
            });

      - name: Fail if tests failed
        if: ${{ steps.run-detekt.outcome == 'failure' }}
        run: exit 1