name: Publish package to GitHub Packages

on:
  workflow_run:
    workflows: ["Versioning"]
    types: [completed]
    branches:
      - main
      - next

  workflow_dispatch:

jobs:
  publish-sdk:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      - name: Publish package
        run: ./gradlew publishAllPublicationsToGitHubPackagesRepository
        env:
          USERNAME_GITHUB: ${{ github.actor }}
          TOKEN_GITHUB: ${{ secrets.GITHUB_TOKEN }}
