name: Run Unit Tests

on:
  pull_request:
    branches:
      - 'develop'
    types: [opened, reopened, synchronize]

permissions:
  contents: read
  pull-requests: write

jobs:
  unit-tests:
    name: Unit Tests Debug
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      - name: Run unit tests in debug mode
        id: run-tests
        run: ./gradlew automotive:testDebugUnitTest
        continue-on-error: true

      - name: Upload test reports
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: '**/build/reports/tests/testDebugUnitTest'

      - name: Comment on PR
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions/github-script@v7
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const outcomeTest = '${{ steps.run-tests.outcome }}';
            
            const testMessage = outcomeTest === 'success' 
              ? `✅ All tests in debug mode passed successfully!`
              : `❌ Some tests in debug mode failed. Please check the gradle report artifact.`;
            
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: testMessage
            });

      - name: Fail if tests failed
        if: ${{ steps.run-tests.outcome == 'failure' || steps.run-detekt.outcome == 'failure' }}
        run: exit 1