name: Run Unit Tests

on:
  pull_request:
    branches:
      - 'develop'

permissions:
  contents: read
  pull-requests: write

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      - name: Run unit tests
        id: run-tests
        run: ./gradlew automotive:testReleaseUnitTest
        continue-on-error: true

      - name: Upload HTML test reports
        uses: actions/upload-artifact@v4
        with:
          name: html-report
          path: '**/build/reports/tests/testReleaseUnitTest'

      - name: Comment on PR
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions/github-script@v7
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const outcome = '${{ steps.run-tests.outcome }}';
            
            const runId = process.env.GITHUB_RUN_ID;
            const artifacts = await github.rest.actions.listWorkflowRunArtifacts({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: runId
            });
            
            const artifact = artifacts.data.artifacts.find(a => a.name === 'html-report');
            const reportUrl = artifact ? artifact.archive_download_url : null;

            const message = outcome === 'success' 
              ? `✅ All tests passed successfully!\n${reportUrl ? `Report url: ${reportUrl}` : "No report artifact found."}`
              : `❌ Some tests failed. Please check the logs.\n${reportUrl ? `Report url: ${reportUrl}` : "No report artifact found."}`;
            
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: message
            });

      - name: Fail if tests failed
        if: steps.run-tests.outcome == 'failure'
        run: exit 1