name: Run Unit Tests

on:
  pull_request:
    branches:
      - develop

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      - name: Run unit tests
        id: run-tests
        run: ./gradlew automotive:testReleaseUnitTest
        continue-on-error: true

      - name: Upload JUnit test results
        uses: actions/upload-artifact@v4
        with:
          name: junit-results
          path: '**/build/test-results/testReleaseUnitTest'

      - name: Upload HTML test reports
        uses: actions/upload-artifact@v4
        with:
          name: html-report
          path: '**/build/reports/tests/testReleaseUnitTest'

      - name: Comment on PR
        if: ${{ github.event_name == 'pull_request' }}
        uses: peter-evans/create-or-update-comment@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
              ${{ steps.run-tests.outcome == 'success' && '✅ All tests passed successfully!' || '❌ Some tests failed. Please check the logs.' }}