name: Versioning

on:
  push:
    branches:
      - 'main'
      - 'next'

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  semantic-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: 'yarn'
          node-version: 22

      - name: Install dependencies
        run: yarn

      - name: Run Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
